### ISSUE TITLE
DriveDok_001_Create_a_DriveDokAdmin_Entity

### ISSUE THREAD

**Issue by GeenEva** [dominicnzl/DriveDok#5]
As a developer I want to create an entity for the DriveDok Administrator.

The DriveDok has a DriveDok Administrator who sets up the DriveDok: he is in charge of the amount of ParkingZones, the amount of electrical spots, timeslots etc.

**Comment by mdeinum** [comment]
Why should this be a separate entity instead of a generic user with a different set of authorities?
